/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lottobuttons;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Objects;

import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class LottoButtonsGUI extends javax.swing.JFrame {
        
    /**
     * Creates new form LottoButtonsGUI
     */
    public LottoButtonsGUI() {
        initComponents();
        result = 0;
        
        //jButton1.setVisible(false);
        //resetBtn.setVisible(false);
        
        /*if(phase1Btn.isEnabled()){
            jButton1.setVisible(false);
            resetBtn.setVisible(false);
        }*/
        
        
        buttonsGroupInvisible();
        
        
    }
    /*This was giving a warning*/
    //ArrayList list = new ArrayList();
    
    //Arrays_2D myArrays_2D = new Arrays_2D();
    
    //ArrayList<Integer> list = new ArrayList<>();
    
    Random r = new Random();
    int result;
    int x;
    boolean phase2 = false;
    boolean P2Lotto = false;
    boolean lottoP1 = false;
    boolean lottoP2 = false;
    
    ArrayList <Integer> list = new ArrayList();
    ArrayList <Integer> lotto = new ArrayList();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        phase1Btn = new javax.swing.JButton();
        phase2Btn = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn38 = new javax.swing.JButton();
        btn39 = new javax.swing.JButton();
        btn40 = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        lblLine1 = new javax.swing.JLabel();
        lblLine2 = new javax.swing.JLabel();
        lblLine3 = new javax.swing.JLabel();
        lblLine2Win = new javax.swing.JLabel();
        lblLine3Win = new javax.swing.JLabel();
        lblChoose = new javax.swing.JLabel();
        lblEnter = new javax.swing.JLabel();
        LoseText = new javax.swing.JLabel();
        WinText = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblLotto = new javax.swing.JButton();
        lblLottoP1 = new javax.swing.JButton();
        lblLottoP2 = new javax.swing.JButton();
        lblText1 = new javax.swing.JLabel();
        lblGuessed = new javax.swing.JLabel();
        replayBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        StartScreenImg = new javax.swing.JLabel();
        BackgroundImg = new javax.swing.JLabel();
        WinScreen = new javax.swing.JLabel();
        LoseScreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LottoApp");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(667, 340));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        phase1Btn.setBackground(new java.awt.Color(207, 181, 59));
        phase1Btn.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        phase1Btn.setText("Phase1");
        phase1Btn.setBorderPainted(false);
        phase1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phase1BtnActionPerformed(evt);
            }
        });
        jPanel1.add(phase1Btn);
        phase1Btn.setBounds(370, 160, 240, 80);

        phase2Btn.setBackground(new java.awt.Color(207, 181, 59));
        phase2Btn.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        phase2Btn.setText("Phase 2");
        phase2Btn.setBorderPainted(false);
        phase2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phase2BtnActionPerformed(evt);
            }
        });
        jPanel1.add(phase2Btn);
        phase2Btn.setBounds(370, 270, 240, 80);

        btn1.setBackground(new java.awt.Color(207, 181, 59));
        btn1.setText("1");
        btn1.setBorderPainted(false);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);
        btn1.setBounds(20, 270, 50, 20);

        btn2.setBackground(new java.awt.Color(207, 181, 59));
        btn2.setText("2");
        btn2.setBorderPainted(false);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);
        btn2.setBounds(80, 270, 50, 20);

        btn3.setBackground(new java.awt.Color(207, 181, 59));
        btn3.setText("3");
        btn3.setBorderPainted(false);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);
        btn3.setBounds(140, 270, 50, 20);

        btn4.setBackground(new java.awt.Color(207, 181, 59));
        btn4.setText("4");
        btn4.setBorderPainted(false);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);
        btn4.setBounds(200, 270, 50, 20);

        btn5.setBackground(new java.awt.Color(207, 181, 59));
        btn5.setText("5");
        btn5.setBorderPainted(false);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);
        btn5.setBounds(260, 270, 50, 20);

        btn6.setBackground(new java.awt.Color(207, 181, 59));
        btn6.setText("6");
        btn6.setBorderPainted(false);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);
        btn6.setBounds(320, 270, 50, 20);

        btn7.setBackground(new java.awt.Color(207, 181, 59));
        btn7.setText("7");
        btn7.setBorderPainted(false);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);
        btn7.setBounds(380, 270, 50, 20);

        btn8.setBackground(new java.awt.Color(207, 181, 59));
        btn8.setText("8");
        btn8.setBorderPainted(false);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);
        btn8.setBounds(440, 270, 50, 20);

        btn9.setBackground(new java.awt.Color(207, 181, 59));
        btn9.setText("9");
        btn9.setBorderPainted(false);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);
        btn9.setBounds(500, 270, 50, 20);

        btn10.setBackground(new java.awt.Color(207, 181, 59));
        btn10.setText("10");
        btn10.setBorderPainted(false);
        btn10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn10.setMaximumSize(new java.awt.Dimension(39, 23));
        btn10.setMinimumSize(new java.awt.Dimension(39, 23));
        btn10.setPreferredSize(new java.awt.Dimension(39, 23));
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        jPanel1.add(btn10);
        btn10.setBounds(560, 270, 50, 20);

        btn11.setBackground(new java.awt.Color(207, 181, 59));
        btn11.setText("11");
        btn11.setBorderPainted(false);
        btn11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn11.setMaximumSize(new java.awt.Dimension(39, 23));
        btn11.setMinimumSize(new java.awt.Dimension(39, 23));
        btn11.setPreferredSize(new java.awt.Dimension(39, 23));
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        jPanel1.add(btn11);
        btn11.setBounds(20, 300, 50, 20);

        btn12.setBackground(new java.awt.Color(207, 181, 59));
        btn12.setText("12");
        btn12.setBorderPainted(false);
        btn12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn12.setMaximumSize(new java.awt.Dimension(39, 23));
        btn12.setMinimumSize(new java.awt.Dimension(39, 23));
        btn12.setPreferredSize(new java.awt.Dimension(39, 23));
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        jPanel1.add(btn12);
        btn12.setBounds(80, 300, 50, 20);

        btn13.setBackground(new java.awt.Color(207, 181, 59));
        btn13.setText("13");
        btn13.setBorderPainted(false);
        btn13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn13.setMaximumSize(new java.awt.Dimension(39, 23));
        btn13.setMinimumSize(new java.awt.Dimension(39, 23));
        btn13.setPreferredSize(new java.awt.Dimension(39, 23));
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        jPanel1.add(btn13);
        btn13.setBounds(140, 300, 50, 20);

        btn14.setBackground(new java.awt.Color(207, 181, 59));
        btn14.setText("14");
        btn14.setBorderPainted(false);
        btn14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn14.setMaximumSize(new java.awt.Dimension(39, 23));
        btn14.setMinimumSize(new java.awt.Dimension(39, 23));
        btn14.setPreferredSize(new java.awt.Dimension(39, 23));
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });
        jPanel1.add(btn14);
        btn14.setBounds(200, 300, 50, 20);

        btn15.setBackground(new java.awt.Color(207, 181, 59));
        btn15.setText("15");
        btn15.setBorderPainted(false);
        btn15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn15.setMaximumSize(new java.awt.Dimension(39, 23));
        btn15.setMinimumSize(new java.awt.Dimension(39, 23));
        btn15.setPreferredSize(new java.awt.Dimension(39, 23));
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });
        jPanel1.add(btn15);
        btn15.setBounds(260, 300, 50, 20);

        btn16.setBackground(new java.awt.Color(207, 181, 59));
        btn16.setText("16");
        btn16.setBorderPainted(false);
        btn16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn16.setMaximumSize(new java.awt.Dimension(39, 23));
        btn16.setMinimumSize(new java.awt.Dimension(39, 23));
        btn16.setPreferredSize(new java.awt.Dimension(39, 23));
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });
        jPanel1.add(btn16);
        btn16.setBounds(320, 300, 50, 20);

        btn17.setBackground(new java.awt.Color(207, 181, 59));
        btn17.setText("17");
        btn17.setBorderPainted(false);
        btn17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn17.setMaximumSize(new java.awt.Dimension(39, 23));
        btn17.setMinimumSize(new java.awt.Dimension(39, 23));
        btn17.setPreferredSize(new java.awt.Dimension(39, 23));
        btn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn17ActionPerformed(evt);
            }
        });
        jPanel1.add(btn17);
        btn17.setBounds(380, 300, 50, 20);

        btn18.setBackground(new java.awt.Color(207, 181, 59));
        btn18.setText("18");
        btn18.setBorderPainted(false);
        btn18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn18.setMaximumSize(new java.awt.Dimension(39, 23));
        btn18.setMinimumSize(new java.awt.Dimension(39, 23));
        btn18.setPreferredSize(new java.awt.Dimension(39, 23));
        btn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn18ActionPerformed(evt);
            }
        });
        jPanel1.add(btn18);
        btn18.setBounds(440, 300, 50, 20);

        btn19.setBackground(new java.awt.Color(207, 181, 59));
        btn19.setText("19");
        btn19.setBorderPainted(false);
        btn19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn19.setMaximumSize(new java.awt.Dimension(39, 23));
        btn19.setMinimumSize(new java.awt.Dimension(39, 23));
        btn19.setPreferredSize(new java.awt.Dimension(39, 23));
        btn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn19ActionPerformed(evt);
            }
        });
        jPanel1.add(btn19);
        btn19.setBounds(500, 300, 50, 20);

        btn20.setBackground(new java.awt.Color(207, 181, 59));
        btn20.setText("20");
        btn20.setBorderPainted(false);
        btn20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn20.setMaximumSize(new java.awt.Dimension(39, 23));
        btn20.setMinimumSize(new java.awt.Dimension(39, 23));
        btn20.setPreferredSize(new java.awt.Dimension(39, 23));
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        jPanel1.add(btn20);
        btn20.setBounds(560, 300, 50, 20);

        btn21.setBackground(new java.awt.Color(207, 181, 59));
        btn21.setText("21");
        btn21.setBorderPainted(false);
        btn21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn21.setMaximumSize(new java.awt.Dimension(39, 23));
        btn21.setMinimumSize(new java.awt.Dimension(39, 23));
        btn21.setPreferredSize(new java.awt.Dimension(39, 23));
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        jPanel1.add(btn21);
        btn21.setBounds(20, 330, 50, 20);

        btn22.setBackground(new java.awt.Color(207, 181, 59));
        btn22.setText("22");
        btn22.setBorderPainted(false);
        btn22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn22.setMaximumSize(new java.awt.Dimension(39, 23));
        btn22.setMinimumSize(new java.awt.Dimension(39, 23));
        btn22.setPreferredSize(new java.awt.Dimension(39, 23));
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        jPanel1.add(btn22);
        btn22.setBounds(80, 330, 50, 20);

        btn23.setBackground(new java.awt.Color(207, 181, 59));
        btn23.setText("23");
        btn23.setBorderPainted(false);
        btn23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn23.setMaximumSize(new java.awt.Dimension(39, 23));
        btn23.setMinimumSize(new java.awt.Dimension(39, 23));
        btn23.setPreferredSize(new java.awt.Dimension(39, 23));
        btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn23ActionPerformed(evt);
            }
        });
        jPanel1.add(btn23);
        btn23.setBounds(140, 330, 50, 20);

        btn24.setBackground(new java.awt.Color(207, 181, 59));
        btn24.setText("24");
        btn24.setBorderPainted(false);
        btn24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn24.setMaximumSize(new java.awt.Dimension(39, 23));
        btn24.setMinimumSize(new java.awt.Dimension(39, 23));
        btn24.setPreferredSize(new java.awt.Dimension(39, 23));
        btn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn24ActionPerformed(evt);
            }
        });
        jPanel1.add(btn24);
        btn24.setBounds(200, 330, 50, 20);

        btn25.setBackground(new java.awt.Color(207, 181, 59));
        btn25.setText("25");
        btn25.setBorderPainted(false);
        btn25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn25.setMaximumSize(new java.awt.Dimension(39, 23));
        btn25.setMinimumSize(new java.awt.Dimension(39, 23));
        btn25.setPreferredSize(new java.awt.Dimension(39, 23));
        btn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn25ActionPerformed(evt);
            }
        });
        jPanel1.add(btn25);
        btn25.setBounds(260, 330, 50, 20);

        btn26.setBackground(new java.awt.Color(207, 181, 59));
        btn26.setText("26");
        btn26.setBorderPainted(false);
        btn26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn26.setMaximumSize(new java.awt.Dimension(39, 23));
        btn26.setMinimumSize(new java.awt.Dimension(39, 23));
        btn26.setPreferredSize(new java.awt.Dimension(39, 23));
        btn26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn26ActionPerformed(evt);
            }
        });
        jPanel1.add(btn26);
        btn26.setBounds(320, 330, 50, 20);

        btn27.setBackground(new java.awt.Color(207, 181, 59));
        btn27.setText("27");
        btn27.setBorderPainted(false);
        btn27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn27.setMaximumSize(new java.awt.Dimension(39, 23));
        btn27.setMinimumSize(new java.awt.Dimension(39, 23));
        btn27.setPreferredSize(new java.awt.Dimension(39, 23));
        btn27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn27ActionPerformed(evt);
            }
        });
        jPanel1.add(btn27);
        btn27.setBounds(380, 330, 50, 20);

        btn28.setBackground(new java.awt.Color(207, 181, 59));
        btn28.setText("28");
        btn28.setBorderPainted(false);
        btn28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn28.setMaximumSize(new java.awt.Dimension(39, 23));
        btn28.setMinimumSize(new java.awt.Dimension(39, 23));
        btn28.setPreferredSize(new java.awt.Dimension(39, 23));
        btn28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn28ActionPerformed(evt);
            }
        });
        jPanel1.add(btn28);
        btn28.setBounds(440, 330, 50, 20);

        btn29.setBackground(new java.awt.Color(207, 181, 59));
        btn29.setText("29");
        btn29.setBorderPainted(false);
        btn29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn29.setMaximumSize(new java.awt.Dimension(39, 23));
        btn29.setMinimumSize(new java.awt.Dimension(39, 23));
        btn29.setPreferredSize(new java.awt.Dimension(39, 23));
        btn29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn29ActionPerformed(evt);
            }
        });
        jPanel1.add(btn29);
        btn29.setBounds(500, 330, 50, 20);

        btn30.setBackground(new java.awt.Color(207, 181, 59));
        btn30.setText("30");
        btn30.setBorderPainted(false);
        btn30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn30.setMaximumSize(new java.awt.Dimension(39, 23));
        btn30.setMinimumSize(new java.awt.Dimension(39, 23));
        btn30.setPreferredSize(new java.awt.Dimension(39, 23));
        btn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30ActionPerformed(evt);
            }
        });
        jPanel1.add(btn30);
        btn30.setBounds(560, 330, 50, 20);

        btn31.setBackground(new java.awt.Color(207, 181, 59));
        btn31.setText("31");
        btn31.setBorderPainted(false);
        btn31.setMaximumSize(new java.awt.Dimension(39, 23));
        btn31.setMinimumSize(new java.awt.Dimension(39, 23));
        btn31.setPreferredSize(new java.awt.Dimension(39, 23));
        btn31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn31ActionPerformed(evt);
            }
        });
        jPanel1.add(btn31);
        btn31.setBounds(20, 360, 50, 20);

        btn32.setBackground(new java.awt.Color(207, 181, 59));
        btn32.setText("32");
        btn32.setBorderPainted(false);
        btn32.setMaximumSize(new java.awt.Dimension(39, 23));
        btn32.setMinimumSize(new java.awt.Dimension(39, 23));
        btn32.setPreferredSize(new java.awt.Dimension(39, 23));
        btn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn32ActionPerformed(evt);
            }
        });
        jPanel1.add(btn32);
        btn32.setBounds(80, 360, 50, 20);

        btn33.setBackground(new java.awt.Color(207, 181, 59));
        btn33.setText("33");
        btn33.setBorderPainted(false);
        btn33.setMaximumSize(new java.awt.Dimension(39, 23));
        btn33.setMinimumSize(new java.awt.Dimension(39, 23));
        btn33.setPreferredSize(new java.awt.Dimension(39, 23));
        btn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn33ActionPerformed(evt);
            }
        });
        jPanel1.add(btn33);
        btn33.setBounds(140, 360, 50, 20);

        btn34.setBackground(new java.awt.Color(207, 181, 59));
        btn34.setText("34");
        btn34.setBorderPainted(false);
        btn34.setMaximumSize(new java.awt.Dimension(39, 23));
        btn34.setMinimumSize(new java.awt.Dimension(39, 23));
        btn34.setPreferredSize(new java.awt.Dimension(39, 23));
        btn34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn34ActionPerformed(evt);
            }
        });
        jPanel1.add(btn34);
        btn34.setBounds(200, 360, 50, 20);

        btn35.setBackground(new java.awt.Color(207, 181, 59));
        btn35.setText("35");
        btn35.setBorderPainted(false);
        btn35.setMaximumSize(new java.awt.Dimension(39, 23));
        btn35.setMinimumSize(new java.awt.Dimension(39, 23));
        btn35.setPreferredSize(new java.awt.Dimension(39, 23));
        btn35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn35ActionPerformed(evt);
            }
        });
        jPanel1.add(btn35);
        btn35.setBounds(260, 360, 50, 20);

        btn36.setBackground(new java.awt.Color(207, 181, 59));
        btn36.setText("36");
        btn36.setBorderPainted(false);
        btn36.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn36.setMaximumSize(new java.awt.Dimension(39, 23));
        btn36.setMinimumSize(new java.awt.Dimension(39, 23));
        btn36.setPreferredSize(new java.awt.Dimension(39, 23));
        btn36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn36ActionPerformed(evt);
            }
        });
        jPanel1.add(btn36);
        btn36.setBounds(320, 360, 50, 20);

        btn37.setBackground(new java.awt.Color(207, 181, 59));
        btn37.setText("37");
        btn37.setBorderPainted(false);
        btn37.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn37.setMaximumSize(new java.awt.Dimension(39, 23));
        btn37.setMinimumSize(new java.awt.Dimension(39, 23));
        btn37.setPreferredSize(new java.awt.Dimension(39, 23));
        btn37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn37ActionPerformed(evt);
            }
        });
        jPanel1.add(btn37);
        btn37.setBounds(380, 360, 50, 20);

        btn38.setBackground(new java.awt.Color(207, 181, 59));
        btn38.setText("38");
        btn38.setBorderPainted(false);
        btn38.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn38.setMaximumSize(new java.awt.Dimension(39, 23));
        btn38.setMinimumSize(new java.awt.Dimension(39, 23));
        btn38.setPreferredSize(new java.awt.Dimension(39, 23));
        btn38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn38ActionPerformed(evt);
            }
        });
        jPanel1.add(btn38);
        btn38.setBounds(440, 360, 50, 20);

        btn39.setBackground(new java.awt.Color(207, 181, 59));
        btn39.setText("39");
        btn39.setBorderPainted(false);
        btn39.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn39.setMaximumSize(new java.awt.Dimension(39, 23));
        btn39.setMinimumSize(new java.awt.Dimension(39, 23));
        btn39.setPreferredSize(new java.awt.Dimension(39, 23));
        btn39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn39ActionPerformed(evt);
            }
        });
        jPanel1.add(btn39);
        btn39.setBounds(500, 360, 50, 20);

        btn40.setBackground(new java.awt.Color(207, 181, 59));
        btn40.setText("40");
        btn40.setBorderPainted(false);
        btn40.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn40.setMaximumSize(new java.awt.Dimension(39, 23));
        btn40.setMinimumSize(new java.awt.Dimension(39, 23));
        btn40.setPreferredSize(new java.awt.Dimension(39, 23));
        btn40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn40ActionPerformed(evt);
            }
        });
        jPanel1.add(btn40);
        btn40.setBounds(560, 360, 50, 20);

        resetBtn.setBackground(new java.awt.Color(207, 181, 59));
        resetBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.setBorderPainted(false);
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn);
        resetBtn.setBounds(320, 390, 90, 23);

        btnSave.setBackground(new java.awt.Color(207, 181, 59));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorderPainted(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(400, 240, 73, 23);

        btnLoad.setBackground(new java.awt.Color(207, 181, 59));
        btnLoad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLoad.setText("Load");
        btnLoad.setBorderPainted(false);
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoad);
        btnLoad.setBounds(170, 240, 70, 23);

        lblLine1.setForeground(new java.awt.Color(207, 181, 59));
        lblLine1.setText("Line 1");
        jPanel1.add(lblLine1);
        lblLine1.setBounds(350, 160, 40, 14);

        lblLine2.setForeground(new java.awt.Color(207, 181, 59));
        lblLine2.setText("Line 2");
        jPanel1.add(lblLine2);
        lblLine2.setBounds(350, 190, 34, 14);

        lblLine3.setForeground(new java.awt.Color(207, 181, 59));
        lblLine3.setText("Line 3");
        jPanel1.add(lblLine3);
        lblLine3.setBounds(350, 220, 34, 14);

        lblLine2Win.setForeground(new java.awt.Color(207, 181, 59));
        jPanel1.add(lblLine2Win);
        lblLine2Win.setBounds(400, 190, 120, 20);

        lblLine3Win.setForeground(new java.awt.Color(207, 181, 59));
        jPanel1.add(lblLine3Win);
        lblLine3Win.setBounds(400, 220, 120, 20);

        lblChoose.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        lblChoose.setForeground(new java.awt.Color(207, 181, 59));
        lblChoose.setText("Choose a Lotto game");
        jPanel1.add(lblChoose);
        lblChoose.setBounds(180, 140, 290, 50);

        lblEnter.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        lblEnter.setForeground(new java.awt.Color(207, 181, 59));
        lblEnter.setText("Enter your Lotto numbers");
        jPanel1.add(lblEnter);
        lblEnter.setBounds(150, 140, 330, 50);

        LoseText.setFont(new java.awt.Font("Edwardian Script ITC", 1, 48)); // NOI18N
        LoseText.setForeground(new java.awt.Color(207, 181, 59));
        LoseText.setText("You Lose!");
        jPanel1.add(LoseText);
        LoseText.setBounds(340, 40, 210, 50);

        WinText.setFont(new java.awt.Font("Edwardian Script ITC", 1, 48)); // NOI18N
        WinText.setForeground(new java.awt.Color(207, 181, 59));
        WinText.setText("You Win!");
        jPanel1.add(WinText);
        WinText.setBounds(340, 40, 220, 50);

        lbl1.setForeground(new java.awt.Color(207, 181, 59));
        jPanel1.add(lbl1);
        lbl1.setBounds(400, 160, 140, 20);

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl2.setForeground(new java.awt.Color(207, 181, 59));
        lbl2.setText("Winning Numbers");
        jPanel1.add(lbl2);
        lbl2.setBounds(350, 130, 120, 20);

        jButton1.setBackground(new java.awt.Color(207, 181, 59));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Submit Numbers");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 390, 130, 23);

        lblLotto.setBackground(new java.awt.Color(207, 181, 59));
        lblLotto.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        lblLotto.setText("Lotto");
        lblLotto.setBorderPainted(false);
        lblLotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLottoActionPerformed(evt);
            }
        });
        jPanel1.add(lblLotto);
        lblLotto.setBounds(120, 190, 120, 50);

        lblLottoP1.setBackground(new java.awt.Color(207, 181, 59));
        lblLottoP1.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        lblLottoP1.setText("LottoPlus1");
        lblLottoP1.setBorderPainted(false);
        lblLottoP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLottoP1ActionPerformed(evt);
            }
        });
        jPanel1.add(lblLottoP1);
        lblLottoP1.setBounds(260, 190, 120, 50);

        lblLottoP2.setBackground(new java.awt.Color(207, 181, 59));
        lblLottoP2.setFont(new java.awt.Font("Edwardian Script ITC", 0, 24)); // NOI18N
        lblLottoP2.setText("LottoPlus2");
        lblLottoP2.setBorderPainted(false);
        lblLottoP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLottoP2ActionPerformed(evt);
            }
        });
        jPanel1.add(lblLottoP2);
        lblLottoP2.setBounds(400, 190, 120, 50);

        lblText1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblText1.setForeground(new java.awt.Color(207, 181, 59));
        lblText1.setText("You have       numbers correct!");
        jPanel1.add(lblText1);
        lblText1.setBounds(350, 100, 270, 20);

        lblGuessed.setForeground(new java.awt.Color(207, 181, 59));
        jPanel1.add(lblGuessed);
        lblGuessed.setBounds(410, 100, 60, 20);

        replayBtn.setBackground(new java.awt.Color(207, 181, 59));
        replayBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        replayBtn.setText("Replay");
        replayBtn.setBorderPainted(false);
        replayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(replayBtn);
        replayBtn.setBounds(520, 210, 90, 23);

        exitBtn.setBackground(new java.awt.Color(207, 181, 59));
        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setBorderPainted(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn);
        exitBtn.setBounds(520, 240, 90, 23);

        StartScreenImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lottobuttons/start.jpg"))); // NOI18N
        jPanel1.add(StartScreenImg);
        StartScreenImg.setBounds(0, 0, 630, 430);

        BackgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lottobuttons/background.jpg"))); // NOI18N
        jPanel1.add(BackgroundImg);
        BackgroundImg.setBounds(0, 0, 630, 430);

        WinScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lottobuttons/WinScreen.jpg"))); // NOI18N
        jPanel1.add(WinScreen);
        WinScreen.setBounds(0, 0, 630, 430);

        LoseScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lottobuttons/LoseScreen.jpg"))); // NOI18N
        jPanel1.add(LoseScreen);
        LoseScreen.setBounds(0, 0, 630, 430);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        btn1.setEnabled(false);
        list.add(1);
        /*if(list.size()>=5){
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
        }*/
        buttonsGroupDisable();
    }//GEN-LAST:event_btn1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(list);
        System.out.println(lottoP2);
        if(lottoP2==true){        
            Randomize();
            Randomize();
            Randomize();
            lblLine2Win.setVisible(true);
            lblLine3Win.setVisible(true);
            lblLine1.setVisible(true);
            lblLine2.setVisible(true);
            lblLine3.setVisible(true);
            
        }
        else if(lottoP1==true){
            Randomize();
            Randomize();
            lblLine2Win.setVisible(true);
            lblLine1.setVisible(true);
            lblLine2.setVisible(true);
        }
        else{
            Randomize();
            lblLine1.setVisible(true);
        }
       
       
       advancePhase();
        
        jButton1.setVisible(false);
        resetBtn.setVisible(false);
        if(x!=2){
            replayBtn.setVisible(true);
        }
        exitBtn.setVisible(true);
        lblText1.setVisible(true);
        lbl2.setVisible(true);
    
        lblGuessed.setVisible(true);
        lbl1.setVisible(true);
        lblEnter.setVisible(false);
        btnLoad.setVisible(false);
        btnSave.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        btn2.setEnabled(false);
        list.add(2);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        btn3.setEnabled(false);
        list.add(3);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        btn4.setEnabled(false);
        list.add(4);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        btn5.setEnabled(false);
        list.add(5);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        btn6.setEnabled(false);
        list.add(6);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        btn7.setEnabled(false);
        list.add(7);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        btn8.setEnabled(false);
        list.add(8);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        btn9.setEnabled(false);
        list.add(9);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
        btn10.setEnabled(false);
        list.add(10);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn10ActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        buttonsGroupEnable();
        list.clear();
        lotto.clear();
        resetBtn.setVisible(false);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
        btn11.setEnabled(false);
        list.add(11);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
        btn12.setEnabled(false);
        list.add(12);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        // TODO add your handling code here:
        btn13.setEnabled(false);
        list.add(13);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        // TODO add your handling code here:
        btn14.setEnabled(false);
        list.add(14);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        // TODO add your handling code here:
        btn15.setEnabled(false);
        list.add(15);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        // TODO add your handling code here:
        btn16.setEnabled(false);
        list.add(16);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn16ActionPerformed

    private void btn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn17ActionPerformed
        // TODO add your handling code here:
        btn17.setEnabled(false);
        list.add(17);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn17ActionPerformed

    private void btn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn18ActionPerformed
        // TODO add your handling code here:
        btn18.setEnabled(false);
        list.add(18);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn18ActionPerformed

    private void btn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn19ActionPerformed
        // TODO add your handling code here:
        btn19.setEnabled(false);
        list.add(19);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn19ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
        btn20.setEnabled(false);
        list.add(20);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        // TODO add your handling code here:
        btn21.setEnabled(false);
        list.add(21);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        // TODO add your handling code here:
        btn22.setEnabled(false);
        list.add(22);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn23ActionPerformed
        // TODO add your handling code here:
        btn23.setEnabled(false);
        list.add(23);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn23ActionPerformed

    private void btn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn24ActionPerformed
        // TODO add your handling code here:
        btn24.setEnabled(false);
        list.add(24);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn24ActionPerformed

    private void btn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn25ActionPerformed
        // TODO add your handling code here:
        btn25.setEnabled(false);
        list.add(25);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn25ActionPerformed

    private void btn26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn26ActionPerformed
        // TODO add your handling code here:
        btn26.setEnabled(false);
        list.add(26);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn26ActionPerformed

    private void btn27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn27ActionPerformed
        // TODO add your handling code here:
        btn27.setEnabled(false);
        list.add(27);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn27ActionPerformed

    private void btn28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn28ActionPerformed
        // TODO add your handling code here:
        btn28.setEnabled(false);
        list.add(28);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn28ActionPerformed

    private void btn29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn29ActionPerformed
        // TODO add your handling code here:
        btn29.setEnabled(false);
        list.add(29);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn29ActionPerformed

    private void btn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30ActionPerformed
        // TODO add your handling code here:
        btn30.setEnabled(false);
        list.add(30);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn30ActionPerformed

    private void btn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn31ActionPerformed
        // TODO add your handling code here:
        btn31.setEnabled(false);
        list.add(31);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn31ActionPerformed

    private void btn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn32ActionPerformed
        // TODO add your handling code here:
        btn32.setEnabled(false);
        list.add(32);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn32ActionPerformed

    private void btn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn33ActionPerformed
        // TODO add your handling code here:
        btn33.setEnabled(false);
        list.add(33);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn33ActionPerformed

    private void btn34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn34ActionPerformed
        // TODO add your handling code here:
        btn34.setEnabled(false);
        list.add(34);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn34ActionPerformed

    private void btn35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn35ActionPerformed
        // TODO add your handling code here:
        btn35.setEnabled(false);
        list.add(35);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn35ActionPerformed

    private void btn36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn36ActionPerformed
        // TODO add your handling code here:
        btn36.setEnabled(false);
        list.add(36);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn36ActionPerformed

    private void btn37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn37ActionPerformed
        // TODO add your handling code here:
        btn37.setEnabled(false);
        list.add(37);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn37ActionPerformed

    private void btn38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn38ActionPerformed
        // TODO add your handling code here:
        btn38.setEnabled(false);
        list.add(38);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn38ActionPerformed

    private void btn39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn39ActionPerformed
        // TODO add your handling code here:
        btn39.setEnabled(false);
        list.add(39);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn39ActionPerformed

    private void btn40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn40ActionPerformed
        // TODO add your handling code here:
        btn40.setEnabled(false);
        list.add(40);
        buttonsGroupDisable();
    }//GEN-LAST:event_btn40ActionPerformed

    private void phase1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phase1BtnActionPerformed
        // TODO add your handling code here:
        
        
        phase1Btn.setVisible(false);
        phase2Btn.setVisible(false);
        StartScreenImg.setVisible(false);
        BackgroundImg.setVisible(true);
        buttonsGroupVisible();
        //randomizer
        //myArrays_2D.compute1();
    }//GEN-LAST:event_phase1BtnActionPerformed

    private void phase2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phase2BtnActionPerformed
        // TODO add your handling code here:
        
        phase1Btn.setVisible(false);
        phase2Btn.setVisible(false);
        StartScreenImg.setVisible(false);
        BackgroundImg.setVisible(true);
        lblChoose.setVisible(true);
        lblLotto.setVisible(true);
        lblLottoP1.setVisible(true);
        lblLottoP2.setVisible(true);
        phase2 = true;
        
        
    }//GEN-LAST:event_phase2BtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        //LottoButtonsGUI.dispose();
        this.dispose();
        
    }//GEN-LAST:event_exitBtnActionPerformed

    private void replayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replayBtnActionPerformed
        // TODO add your handling code here:
        BackgroundImg.setVisible(true);
        if(phase1Btn.isEnabled()){
            if(x!=2){
                buttonsGroupEnable();
                list.clear();
                lotto.clear();
                lblGuessed.setVisible(false);
                lbl1.setVisible(false);
                lbl2.setVisible(false);
                lblLine3.setVisible(false);
                lblLine2.setVisible(false);
                lblLine1.setVisible(false);
                LoseText.setVisible(false);
                WinText.setVisible(false);
                
                lblText1.setVisible(false);
                resetBtn.setVisible(false);
                btnLoad.setVisible(true);
                btnSave.setVisible(true);
                x++;
                if(x==2){
                    replayBtn.setVisible(false);
                }
            }

            result=0;
        }
        if(phase2==true){
            buttonsGroupInvisible();
            lblLotto.setVisible(true);
            lblLottoP1.setVisible(true);
            lblLottoP2.setVisible(true);
            lbl1.setVisible(false);
            lblGuessed.setVisible(false);
            lblLine2Win.setVisible(false);
            lblLine3Win.setVisible(false);
            btnLoad.setVisible(false);
            btnSave.setVisible(false);
        }//End if
    }//GEN-LAST:event_replayBtnActionPerformed

    private void lblLottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLottoActionPerformed
        // TODO add your handling code here:
        phase1Btn.setVisible(false);
        phase2Btn.setVisible(false);
        lblLotto.setVisible(false);
        lblLottoP1.setVisible(false);
        lblLottoP2.setVisible(false);
        
        buttonsGroupVisible();
        
    }//GEN-LAST:event_lblLottoActionPerformed

    private void lblLottoP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLottoP1ActionPerformed
        // TODO add your handling code here:
        phase1Btn.setVisible(false);
        phase2Btn.setVisible(false);
        lblLotto.setVisible(false);
        lblLottoP1.setVisible(false);
        lblLottoP2.setVisible(false);
        
        lottoP1 = true;
        
        buttonsGroupVisible();
        
    }//GEN-LAST:event_lblLottoP1ActionPerformed

    private void lblLottoP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLottoP2ActionPerformed
        // TODO add your handling code here:
        phase1Btn.setVisible(false);
        phase2Btn.setVisible(false);
        lblLotto.setVisible(false);
        lblLottoP1.setVisible(false);
        lblLottoP2.setVisible(false);
        
        lottoP2 = true;
        
        buttonsGroupVisible();
    }//GEN-LAST:event_lblLottoP2ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        try{
            // 1. Change to allow writing of objects
            File f = new File ("output.dat");
            FileOutputStream os = new FileOutputStream (f);
            ObjectOutputStream outputStream = new ObjectOutputStream (os);

            outputStream.writeObject(list);
            
            outputStream.close();
            JOptionPane.showMessageDialog(null, "Success writing to File: "+f);
            
        }catch(IOException e){
            System.out.println(e.toString() + "Error writing to File");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        try{
            File f = new File ("output.dat");
            FileInputStream inStream = new FileInputStream (f);
            ObjectInputStream oStream = new ObjectInputStream (inStream);

            list  = (ArrayList<Integer>) oStream.readObject();
            
            oStream.close ();
            jButton1.setVisible(true);
            //LoadButtonEnabled();
            //jButton1ActionPerformed(ActionEvent e);
            
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(LottoButtonsGUI.class.getName()).log(Level.SEVERE, null, ex);
        }catch(IOException ex){
             System.out.println(ex.toString() + "Error reading from File");
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LottoButtonsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LottoButtonsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LottoButtonsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LottoButtonsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LottoButtonsGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImg;
    private javax.swing.JLabel LoseScreen;
    private javax.swing.JLabel LoseText;
    private javax.swing.JLabel StartScreenImg;
    private javax.swing.JLabel WinScreen;
    private javax.swing.JLabel WinText;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn38;
    private javax.swing.JButton btn39;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn40;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblChoose;
    private javax.swing.JLabel lblEnter;
    private javax.swing.JLabel lblGuessed;
    private javax.swing.JLabel lblLine1;
    private javax.swing.JLabel lblLine2;
    private javax.swing.JLabel lblLine2Win;
    private javax.swing.JLabel lblLine3;
    private javax.swing.JLabel lblLine3Win;
    private javax.swing.JButton lblLotto;
    private javax.swing.JButton lblLottoP1;
    private javax.swing.JButton lblLottoP2;
    private javax.swing.JLabel lblText1;
    private javax.swing.JButton phase1Btn;
    private javax.swing.JButton phase2Btn;
    private javax.swing.JButton replayBtn;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables

public void buttonsGroupDisable(){
    if(list.size()>=5){
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);
        btn10.setEnabled(false);
        btn11.setEnabled(false);
        btn12.setEnabled(false);
        btn13.setEnabled(false);
        btn14.setEnabled(false);
        btn15.setEnabled(false);
        btn16.setEnabled(false);
        btn17.setEnabled(false);
        btn18.setEnabled(false);
        btn19.setEnabled(false);
        btn20.setEnabled(false);
        btn21.setEnabled(false);
        btn22.setEnabled(false);
        btn23.setEnabled(false);
        btn24.setEnabled(false);
        btn25.setEnabled(false);
        btn26.setEnabled(false);
        btn27.setEnabled(false);
        btn28.setEnabled(false);
        btn29.setEnabled(false);
        btn30.setEnabled(false);
        btn31.setEnabled(false);
        btn32.setEnabled(false);
        btn33.setEnabled(false);
        btn34.setEnabled(false);
        btn35.setEnabled(false);
        btn36.setEnabled(false);
        btn37.setEnabled(false);
        btn38.setEnabled(false);
        btn39.setEnabled(false);
        btn40.setEnabled(false);
        jButton1.setVisible(true);
        lbl2.setVisible(false);
        lblLine2.setVisible(false);
        lblLine3.setVisible(false);
        lblLine1.setVisible(false);
        resetBtn.setVisible(true);
        
    } 
    
}

public void buttonsGroupEnable(){
    
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
        btn10.setEnabled(true);
        btn11.setEnabled(true);
        btn12.setEnabled(true);
        btn13.setEnabled(true);
        btn14.setEnabled(true);
        btn15.setEnabled(true);
        btn16.setEnabled(true);
        btn17.setEnabled(true);
        btn18.setEnabled(true);
        btn19.setEnabled(true);
        btn20.setEnabled(true);
        btn21.setEnabled(true);
        btn22.setEnabled(true);
        btn23.setEnabled(true);
        btn24.setEnabled(true);
        btn25.setEnabled(true);
        btn26.setEnabled(true);
        btn27.setEnabled(true);
        btn28.setEnabled(true);
        btn29.setEnabled(true);
        btn30.setEnabled(true);
        btn31.setEnabled(true);
        btn32.setEnabled(true);
        btn33.setEnabled(true);
        btn34.setEnabled(true);
        btn35.setEnabled(true);
        btn36.setEnabled(true);
        btn37.setEnabled(true);
        btn38.setEnabled(true);
        btn39.setEnabled(true);
        btn40.setEnabled(true);
        jButton1.setEnabled(true);
        jButton1.setVisible(false);
        lblEnter.setVisible(true);
     
    
}

public void buttonsGroupInvisible(){
    if(phase1Btn.isEnabled() || phase2Btn.isEnabled()){
        btn1.setVisible(false);
        btn2.setVisible(false);
        btn3.setVisible(false);
        btn4.setVisible(false);
        btn5.setVisible(false);
        btn6.setVisible(false);
        btn7.setVisible(false);
        btn8.setVisible(false);
        btn9.setVisible(false);
        btn10.setVisible(false);
        btn11.setVisible(false);
        btn12.setVisible(false);
        btn13.setVisible(false);
        btn14.setVisible(false);
        btn15.setVisible(false);
        btn16.setVisible(false);
        btn17.setVisible(false);
        btn18.setVisible(false);
        btn19.setVisible(false);
        btn20.setVisible(false);
        btn21.setVisible(false);
        btn22.setVisible(false);
        btn23.setVisible(false);
        btn24.setVisible(false);
        btn25.setVisible(false);
        btn26.setVisible(false);
        btn27.setVisible(false);
        btn28.setVisible(false);
        btn29.setVisible(false);
        btn30.setVisible(false);
        btn31.setVisible(false);
        btn32.setVisible(false);
        btn33.setVisible(false);
        btn34.setVisible(false);
        btn35.setVisible(false);
        btn36.setVisible(false);
        btn37.setVisible(false);
        btn38.setVisible(false);
        btn39.setVisible(false);
        btn40.setVisible(false);
        jButton1.setVisible(false);
        resetBtn.setVisible(false);
        lbl2.setVisible(false);
        lblLine3.setVisible(false);
        lblLine2.setVisible(false);
        lblLine1.setVisible(false);
        lblLotto.setVisible(false);
        lblLottoP1.setVisible(false);
        lblLottoP2.setVisible(false);
        replayBtn.setVisible(false);
        exitBtn.setVisible(false);
        lblText1.setVisible(false);
        LoseScreen.setVisible(false);
        WinScreen.setVisible(false);
        LoseText.setVisible(false);
        WinText.setVisible(false);
        lblEnter.setVisible(false);
        lblChoose.setVisible(false);
        btnLoad.setVisible(false);
        btnSave.setVisible(false);
    } 
    
}

public void buttonsGroupVisible(){
    if(phase1Btn.isEnabled() || phase2Btn.isEnabled()){
        btn1.setVisible(true);
        btn2.setVisible(true);
        btn3.setVisible(true);
        btn4.setVisible(true);
        btn5.setVisible(true);
        btn6.setVisible(true);
        btn7.setVisible(true);
        btn8.setVisible(true);
        btn9.setVisible(true);
        btn10.setVisible(true);
        btn11.setVisible(true);
        btn12.setVisible(true);
        btn13.setVisible(true);
        btn14.setVisible(true);
        btn15.setVisible(true);
        btn16.setVisible(true);
        btn17.setVisible(true);
        btn18.setVisible(true);
        btn19.setVisible(true);
        btn20.setVisible(true);
        btn21.setVisible(true);
        btn22.setVisible(true);
        btn23.setVisible(true);
        btn24.setVisible(true);
        btn25.setVisible(true);
        btn26.setVisible(true);
        btn27.setVisible(true);
        btn28.setVisible(true);
        btn29.setVisible(true);
        btn30.setVisible(true);
        btn31.setVisible(true);
        btn32.setVisible(true);
        btn33.setVisible(true);
        btn34.setVisible(true);
        btn35.setVisible(true);
        btn36.setVisible(true);
        btn37.setVisible(true);
        btn38.setVisible(true);
        btn39.setVisible(true);
        btn40.setVisible(true);
        jButton1.setVisible(false);
        lbl2.setVisible(false);
        lblLine1.setVisible(false);
        lblLine2.setVisible(false);
        lblLine3.setVisible(false);
        resetBtn.setVisible(false);
        lblEnter.setVisible(true);
        lblChoose.setVisible(false);
        btnLoad.setVisible(true);
        btnSave.setVisible(true);
    } 
    
}

public void Randomize(){
    for (int i = 0; i < 5; i++) {
        lotto.add(r.nextInt((40 - 1) + 1) + 1);
        //Making sure numbers don't repeat
        if (i != 0) {
            for (int h = 1; h <= i; h++) {
                if (Objects.equals(lotto.get(i), lotto.get(i - h))){
                    i--;
                    h--;
                }//End if
            }//End for
        }//End if
        //list2.add(lotto);
    }//end for
    
    }//End Randomizer

public void advancePhase(){
    System.out.println(lotto);
    
    int z;
    if(lottoP1==true){
        z=1;
        lblLine2Win.setText(Integer.toString((int) lotto.get(5)) + " " + Integer.toString((int) lotto.get(6)) + " " + Integer.toString((int) lotto.get(7)) + " " + Integer.toString((int) lotto.get(8)) + " " + Integer.toString((int) lotto.get(9)));
    }
    else if(lottoP2==true){
        z=2;
        lblLine2Win.setText(Integer.toString((int) lotto.get(5)) + " " + Integer.toString((int) lotto.get(6)) + " " + Integer.toString((int) lotto.get(7)) + " " + Integer.toString((int) lotto.get(8)) + " " + Integer.toString((int) lotto.get(9)));
        lblLine3Win.setText(Integer.toString((int) lotto.get(10)) + " " + Integer.toString((int) lotto.get(11)) + " " + Integer.toString((int) lotto.get(12)) + " " + Integer.toString((int) lotto.get(13)) + " " + Integer.toString((int) lotto.get(14)));
    }
    else{
        z=0;
    }
    
    lbl1.setText(Integer.toString((int) lotto.get(0)) + " " + Integer.toString((int) lotto.get(1)) + " " + Integer.toString((int) lotto.get(2)) + " " + Integer.toString((int) lotto.get(3)) + " " + Integer.toString((int) lotto.get(4)));
    //lblLine2Win.setText(Integer.toString((int) lotto.get(5)) + " " + Integer.toString((int) lotto.get(6)) + " " + Integer.toString((int) lotto.get(7)) + " " + Integer.toString((int) lotto.get(8)) + " " + Integer.toString((int) lotto.get(9)));
    //lblLine3Win.setText(Integer.toString((int) lotto.get(10)) + " " + Integer.toString((int) lotto.get(11)) + " " + Integer.toString((int) lotto.get(12)) + " " + Integer.toString((int) lotto.get(13)) + " " + Integer.toString((int) lotto.get(14)));
    
    System.out.println(lotto);
    System.out.println(list);
    System.out.println(z);
    System.out.println(result);
    
    for(int x = 0; x<=z;x++){
        System.out.println("Lotto"+x);
        for (int i = 0; i < 5; i++) {
            System.out.println("List Index "+(i+1));
            for (int j = 0; j < 5; j++) {
                System.out.println("Lotto Index "+(j+1));
                if (Objects.equals(list.get(i), lotto.get(j+(x*5)))) {
                    System.out.println("Correct Guess");
                    result++;
                }//End if
            }//End For
        }//End for
    }//End for
    
    if(result==0){
        System.out.println("Lose");
        BackgroundImg.setVisible(false);
        LoseScreen.setVisible(true);
        LoseText.setVisible(true);
        
    }
    else{
        System.out.println("Win");
        BackgroundImg.setVisible(false);
        WinScreen.setVisible(true);
        WinText.setVisible(true);
    }
    
    System.out.println(result);
    lblGuessed.setText(Integer.toString(result));
}



}//End Class